import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings('ignore')

def is_non_dominated(Y):
    """
    Computes the non-dominated front. 
    Assumes MAXIMIZATION. If minimizing, negate Y before passing.
    """
    is_efficient = np.ones(Y.shape[0], dtype=bool)
    for i, c in enumerate(Y):
        if is_efficient[i]:
            # Keep any point with a lower cost
            is_efficient[is_efficient] &= np.any(Y > c, axis=1) | (np.all(Y == c, axis=1))
            is_efficient[i] = True
    return is_efficient

def load_data(csv_path='baseline_pestcontrol.csv', pt_path='merged_pestcontrol_results.pt'):
    """Loads both the CASMOPOLITAN baseline and the MORBOPOLITAN results."""
    print("Loading data...")
    # 1. Load Baseline (CSV)
    df_baseline = pd.read_csv(csv_path)
    
    # 2. Load Merged Framework (PT)
    # map_location='cpu' ensures it loads safely even without a GPU
    merged_data = torch.load(pt_path, map_location=torch.device('cpu'), weights_only=False)
    
    return df_baseline, merged_data

def plot_convergence(df_baseline, merged_data):
    """Plots the convergence (best value or hypervolume) over evaluations."""
    print("Plotting Convergence...")
    plt.figure(figsize=(10, 6))

    # Baseline Convergence (Goes down)
    baseline_evals = df_baseline['Index'].values
    baseline_best_y = df_baseline['BestValue'].values
    plt.plot(baseline_evals, baseline_best_y, label='Baseline (CASMOPOLITAN)', 
             linewidth=2, linestyle='--', color='blue')

    # --- THE FIX: Plot the exact best_y_history generated by the framework ---
    if "best_y_history" in merged_data and "n_evals" in merged_data:
        best_y = merged_data["best_y_history"]
        evals = merged_data["n_evals"]
        
        plt.plot(evals, best_y, label='Merged (MORBOPOLITAN)', linewidth=2, color='red')
        plt.ylabel('Best Objective Value (Minimized)')
    else:
        print("ERROR: Could not find 'best_y_history' or 'n_evals' in the .pt file!")

    plt.xlabel('Number of Function Evaluations')
    plt.title('Optimization Convergence: Baseline vs. Merged Framework')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('convergence_plot.png')
    plt.show()

def plot_pareto_front(merged_data):
    """Plots the Pareto front if the merged data is multi-objective."""
    print("Checking for Multi-Objective data to plot Pareto Front...")
    y_key = 'metric_history' if 'metric_history' in merged_data else 'all_y'
    
    if y_key not in merged_data:
        print("No evaluation data found to plot Pareto front.")
        return

    merged_y = merged_data[y_key]
    if isinstance(merged_y, torch.Tensor):
        merged_y = merged_y.numpy()

    # Check if multi-objective
    if merged_y.ndim > 1 and merged_y.shape[1] >= 2:
        print("Multi-objective data detected. Plotting Pareto front...")
        
        # Calculate Pareto front (Assuming Maximization, adjust if Minimization)
        pareto_mask = is_non_dominated(merged_y)
        pareto_y = merged_y[pareto_mask]

        plt.figure(figsize=(8, 6))
        
        # Plot all points
        plt.scatter(merged_y[:, 0], merged_y[:, 1], c='lightgray', label='All Evaluated Points', alpha=0.6)
        
        # Plot Pareto points
        plt.scatter(pareto_y[:, 0], pareto_y[:, 1], c='red', label='Pareto Front (Merged)', marker='*', s=100)

        plt.xlabel('Objective 1')
        plt.ylabel('Objective 2')
        plt.title('Discovered Pareto Front (Merged Framework)')
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.savefig('pareto_front_plot.png')
        plt.show()
    else:
        print("Data appears to be single-objective. Skipping Pareto plot.")

def plot_computational_overhead(df_baseline, merged_data):
    """Compares the time per iteration between baseline and merged framework."""
    print("Plotting Computational Overhead...")
    plt.figure(figsize=(10, 6))

    # Baseline Times
    baseline_evals = df_baseline['Index'].values
    baseline_time = df_baseline['Time'].values
    plt.plot(baseline_evals, baseline_time, label='Baseline (CASMOPOLITAN)', 
             linewidth=2, linestyle='--', color='blue')

    # Merged Framework Times
    if 'fit_times' in merged_data and 'gen_times' in merged_data:
        fit_times = np.array(merged_data['fit_times'])
        gen_times = np.array(merged_data['gen_times'])
        
        # Total overhead per batch/iteration
        total_time = fit_times + gen_times
        iterations = range(1, len(total_time) + 1)
        
        plt.plot(iterations, total_time, label='Merged Overhead (Fit + Gen)', 
                 linewidth=2, color='red')
        plt.plot(iterations, fit_times, label='Merged (GP Fit Time)', 
                 linewidth=1, linestyle=':', color='orange')
        plt.plot(iterations, gen_times, label='Merged (Acq Gen Time)', 
                 linewidth=1, linestyle=':', color='green')

    plt.xlabel('Optimization Iterations / Batches')
    plt.ylabel('Wall-clock Time (Seconds)')
    plt.title('Computational Overhead Comparison')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('overhead_plot.png')
    plt.show()

def main():
    csv_path = '/home/nafi/CATO/casmopolitan/baseline_pestcontrol.csv'
    pt_path = 'merged_pestcontrol_results.pt'
    
    if not Path(csv_path).exists() or not Path(pt_path).exists():
        print("Error: Ensure both 'baseline_pestcontrol.csv' and 'merged_pestcontrol_results.pt' are in the current directory.")
        return

    # Load
    df_baseline, merged_data = load_data(csv_path, pt_path)
    
    # Analyze
    plot_convergence(df_baseline, merged_data)
    plot_pareto_front(merged_data)
    plot_computational_overhead(df_baseline, merged_data)
    
    print("Analysis complete. Plots have been saved to your directory.")

if __name__ == '__main__':
    main()